### ISSUE TITLE
The latest version of retype crashes on Windows

### ISSUE THREAD

**Issue by shuen2023** [plu5/retype#18]
When I click to open the book.  retype will automatically close.   

https://github.com/plu5/retype/assets/133501179/0a00f3f6-fa19-4be1-9854-97f529ce97de

**Comment by plu5** [comment]
Should be fixed in [1.3.1](https://github.com/plu5/retype/releases/tag/v1.3.1)! Sorry about that

**Comment by shuen2023** [comment]
> 应该在[1.3.1](https://github.com/plu5/retype/releases/tag/v1.3.1)中修复！对于那个很抱歉

thanks
