### ISSUE TITLE
[Enhancement] Font options

### ISSUE THREAD

**Issue by y124** [plu5/retype#8]
So far i am loving this tool! Just writing to ask if you could add a San-serif typeface such as Roboto or Ubuntu or a font selector as an option, I may try myself but I've never used PyQT5 and i am unfamiliar with the codebase.

**Comment by plu5** [comment]
Thanks for this issue! It looks like when I was implementing the ability to change font size I hard-coded the font and forgot to change it.

https://github.com/plu5/retype/blob/2c7af6a16752b56fdf56b47e4fd8b1326e4efaf5/retype/ui/book_view.py#L31

I will add an option to the settings as soon as I can!

**Comment by y124** [comment]
alright, thanks so much!

**Comment by plu5** [comment]
![2023-05-23-retype-fonts](https://github.com/plu5/retype/assets/8400561/26815f90-e588-48cb-8354-ac69d3fd62ad)

Finished implementing this and it is part of [release 1.1.0](https://github.com/plu5/retype/releases/tag/v1.1.0)
